[book]
authors = ["Ravener"]
language = "en"
multilingual = false
src = "src"
title = "Developing GNOME Applications using Vala and GTK4"

[output.html]
smart-punctuation = true

[output.html.code.hidelines]
cs = "~"
